#!/usr/bin/env Rscript

install.packages("curl")
install.packages("openssl")
install.packages("devtools")
install.packages("optparse")
install.packages("plyr")
install.packages("ggplot2")
install.packages("ggdendro")
install.packages("philentropy")
install.packages("R.utils")
install.packages("xtable")
install.packages("vegan")
install.packages("hash")
install.packages("ape")
install.packages("devtools")
library(devtools)
install_github("igraph/rigraph")
install.packages("networkD3")
